language: node_js
node_js:
- '7'
env:
- NODE_ENV=test
- ANSIBLE_VERSION=2.3.0.0
install:
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
- if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
script:
- ansible-playbook you360/you360_playbook.yml -i you360/hosts --ask-sudo-pass -vvvv
  --flush-cache
deploy:
  provider: releases
  api_key:
    secure: tQbgBunYi/a2UjR71l8IQw8WMVGgiHoDjV7xZJFU3zh90nmArvROuS1iVTH5D5PO5hyZAvh/kfKo+XiK7pQNj1757fy6hP4SKFKiOB/IEg7/qwNHOvVUa8+3wgr/i74m6C2+M58kJYdfXgIjnaMSSn4pD5Ds+xdMUShWvtDeGuzkS9R+SlKsRKPP+a9qlJUfcXuzNn+P2ItXTivW3m2ss4wfx4HP4NYp36gA8Uf2FfilAU+EvGIgUBdMHlS9OEffhycdulGEPZN3PH3+JxSC7vZ4Y+lryFFXWRd9CI1rgV0v+u112M87j/45snGoh12f5Uen+W7ZwnmfKC0oSXa8t4ht1t14xB8mL9cb5BJSUy9UpyJnKcobDVJsz3VSNQdq8YoWtXRNCWn6epI/hv0TPv8Z2ddawLsfvXXOdgT4pfMpkmnqUSufdEkj0saKlMv789fXhtOzlSca277ZoSVIiou1a86OJ2ai0um8daU97ExYXI1/XxwqzGhLkPGRJtsxa6U0iuSIPuR/Jp6GBZZNuKC0Z93nlqf2o3cbBNVt6BWKBTzjj+iT41Ow9Sfp0O1jBKUSCoGTZpupTcOTbHl5EjQRs4F+8J69Eu6SJKgrrxd4H1NldqBJbhgiPJ8RbSi7qmXkggfRxCaBRsUPOMxiy0h/MMo3q4F/NmJmxePCovM=
  file: "*"
  on:
    repo: sayed24/citest
