language: node_js
node_js:
  - "7"
env:
  - NODE_ENV=test
  - ANSIBLE_VERSION=2.3.0.0

install:
  # Install Ansible.
  -  pip install ansible==$ANSIBLE_VERSION

script:
  - ansible-playbook you360/you360_playbook.yml -i you360/hosts --ask-sudo-pass -vvvv --flush-cache
