language: node_js
node_js:
- '7'
env:
- NODE_ENV=test
# script:
# - ansible-playbook you360/you360_playbook.yml -i you360/hosts --ask-sudo-pass -vvvv
#   --flush-cache
# before_deploy:
#   - echo "deploying to GitHub releases"
# before_deploy:
#   - git config --global user.email "builds@travis-ci.com"
#   - git config --global user.name "Travis CI"
#   - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
#   - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
#   - git push origin $GIT_TAG

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/citest --tags
  - ls -R
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: tQbgBunYi/a2UjR71l8IQw8WMVGgiHoDjV7xZJFU3zh90nmArvROuS1iVTH5D5PO5hyZAvh/kfKo+XiK7pQNj1757fy6hP4SKFKiOB/IEg7/qwNHOvVUa8+3wgr/i74m6C2+M58kJYdfXgIjnaMSSn4pD5Ds+xdMUShWvtDeGuzkS9R+SlKsRKPP+a9qlJUfcXuzNn+P2ItXTivW3m2ss4wfx4HP4NYp36gA8Uf2FfilAU+EvGIgUBdMHlS9OEffhycdulGEPZN3PH3+JxSC7vZ4Y+lryFFXWRd9CI1rgV0v+u112M87j/45snGoh12f5Uen+W7ZwnmfKC0oSXa8t4ht1t14xB8mL9cb5BJSUy9UpyJnKcobDVJsz3VSNQdq8YoWtXRNCWn6epI/hv0TPv8Z2ddawLsfvXXOdgT4pfMpkmnqUSufdEkj0saKlMv789fXhtOzlSca277ZoSVIiou1a86OJ2ai0um8daU97ExYXI1/XxwqzGhLkPGRJtsxa6U0iuSIPuR/Jp6GBZZNuKC0Z93nlqf2o3cbBNVt6BWKBTzjj+iT41Ow9Sfp0O1jBKUSCoGTZpupTcOTbHl5EjQRs4F+8J69Eu6SJKgrrxd4H1NldqBJbhgiPJ8RbSi7qmXkggfRxCaBRsUPOMxiy0h/MMo3q4F/NmJmxePCovM=
  file_glob: true
  file: "citest/*"

  on:
    repo: sayed24/citest
    tags: false
    ####################
#################
